/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.0/samples
 */
plugins{
	id("application")
	id("com.github.ben-manes.versions") version "0.54.0"
	id("java")
}

group = "hexlet.code"
version = "1.0.0"

application{
	mainClass = "hexlet.code.App"
}
